### Anotações / Dúvidas
- O que fazer com a data no pré-processamento?
---

# PO-240: Análise Exploratória de Dados

## Bibliotecas

In [66]:
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

## Importando Dados

In [67]:
# Load File
dataset_folder = 'KaggleDatasets/RAW/'
filename = '201702.csv'
dataset = pd.read_csv(dataset_folder + filename)

In [68]:
dataset

,id,date,input_0,input_1,input_2,input_3,input_4_1,input_5_1,input_6_1,input_7_1,...,output_7_6,output_8_6,output_9_6,output_10_6,output_11_6,output_12_6,output_13_6,output_14_6,output_15_6,output_16_6
0,56644,2017-02-01,4,0,213,62,1.642477,-0.206138,0.547687,1.481902,...,2.629011,4.132933,-0.310499,0.974334,1.343431,0.346723,-0.111801,1.026807,2.651589,5.526916
1,56707,2017-02-01,4,1,213,62,-0.026259,-0.206138,-0.653850,-0.617752,...,-0.387950,-0.614713,-0.310499,-0.765870,-0.685337,-0.993390,-0.111801,-0.319206,-0.223367,-0.379209
2,56770,2017-02-01,4,2,213,62,-0.503290,-0.206138,-0.053082,-0.617752,...,-0.723168,-0.614713,-0.310499,-0.632008,-0.779698,-0.695587,-0.111801,-0.126919,-0.510863,-0.379209
3,56833,2017-02-01,4,3,213,62,-0.651817,-0.206138,-0.653850,-0.617752,...,-0.555559,-0.614713,-0.310499,-0.832801,-0.874059,-0.918939,-0.111801,-0.319206,-0.510863,-0.379209
4,43272,2017-02-01,11,0,185,134,0.379130,-0.247257,0.111462,0.256218,...,3.088040,1.315378,0.814293,0.516683,1.453250,0.529982,-0.165694,0.861235,2.598782,-0.593615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,63908,2017-02-28,280,3,44,51,-0.838785,-0.021371,-0.497933,-0.498106,...,-0.581516,-0.415024,-0.121444,-0.734190,-0.724075,-0.581511,-0.052408,-0.592117,-0.588689,-0.408913
2236,64200,2017-02-28,293,0,181,140,0.646477,-0.033802,0.461046,0.081614,...,0.890371,1.646896,-0.086859,1.400603,1.488702,2.576993,-0.045371,4.427106,3.204490,-0.344908
2237,64262,2017-02-28,293,1,181,140,-0.489311,-0.033802,-0.535934,-0.545527,...,-0.563485,-0.541416,-0.086859,-0.705281,-0.660026,-0.208363,-0.045371,0.250198,-0.319559,-0.344908
2238,64324,2017-02-28,293,2,181,140,-0.809080,-0.033802,-0.535934,-0.545527,...,-0.272714,-0.541416,-0.086859,-0.605001,-0.525730,-0.571670,-0.045371,-0.509239,-0.319559,-0.344908
2239,64386,2017-02-28,293,3,181,140,-0.814322,-0.033802,-0.535934,-0.545527,...,-0.563485,-0.541416,-0.086859,-0.705281,-0.727173,-0.692772,-0.045371,-0.509239,-0.526856,-0.344908

In [69]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Columns: 7860 entries, id to output_16_6
dtypes: float64(7854), int64(5), object(1)
memory usage: 134.3+ MB

---

## Pré-Processamento


Será feito:
   - [x] Eliminação Manual de Atributos
   - [ ] ~Integração de dados~
   - [ ] Amostragem & Remoção de Dimensionalidade
   - [ ] Balanceamento de dados
   - [ ] Limpeza de Dados
   - [ ] Transformação de dados

### Eliminação manual de atributos

In [70]:
# ---- Removendo ID e Data ----
dataset = dataset.drop(['id', 'date'], axis=1)

In [71]:
dataset

,input_0,input_1,input_2,input_3,input_4_1,input_5_1,input_6_1,input_7_1,input_8_1,input_9_1,...,output_7_6,output_8_6,output_9_6,output_10_6,output_11_6,output_12_6,output_13_6,output_14_6,output_15_6,output_16_6
0,4,0,213,62,1.642477,-0.206138,0.547687,1.481902,-0.518488,2.424471,...,2.629011,4.132933,-0.310499,0.974334,1.343431,0.346723,-0.111801,1.026807,2.651589,5.526916
1,4,1,213,62,-0.026259,-0.206138,-0.653850,-0.617752,-0.518488,-0.424404,...,-0.387950,-0.614713,-0.310499,-0.765870,-0.685337,-0.993390,-0.111801,-0.319206,-0.223367,-0.379209
2,4,2,213,62,-0.503290,-0.206138,-0.053082,-0.617752,-0.518488,-0.424404,...,-0.723168,-0.614713,-0.310499,-0.632008,-0.779698,-0.695587,-0.111801,-0.126919,-0.510863,-0.379209
3,4,3,213,62,-0.651817,-0.206138,-0.653850,-0.617752,-0.518488,-0.424404,...,-0.555559,-0.614713,-0.310499,-0.832801,-0.874059,-0.918939,-0.111801,-0.319206,-0.510863,-0.379209
4,11,0,185,134,0.379130,-0.247257,0.111462,0.256218,-0.614670,1.661295,...,3.088040,1.315378,0.814293,0.516683,1.453250,0.529982,-0.165694,0.861235,2.598782,-0.593615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,280,3,44,51,-0.838785,-0.021371,-0.497933,-0.498106,-0.318158,-0.032066,...,-0.581516,-0.415024,-0.121444,-0.734190,-0.724075,-0.581511,-0.052408,-0.592117,-0.588689,-0.408913
2236,293,0,181,140,0.646477,-0.033802,0.461046,0.081614,1.376774,-0.052408,...,0.890371,1.646896,-0.086859,1.400603,1.488702,2.576993,-0.045371,4.427106,3.204490,-0.344908
2237,293,1,181,140,-0.489311,-0.033802,-0.535934,-0.545527,-0.471302,-0.052408,...,-0.563485,-0.541416,-0.086859,-0.705281,-0.660026,-0.208363,-0.045371,0.250198,-0.319559,-0.344908
2238,293,2,181,140,-0.809080,-0.033802,-0.535934,-0.545527,-0.471302,-0.052408,...,-0.272714,-0.541416,-0.086859,-0.605001,-0.525730,-0.571670,-0.045371,-0.509239,-0.319559,-0.344908
2239,293,3,181,140,-0.814322,-0.033802,-0.535934,-0.545527,-0.471302,-0.052408,...,-0.563485,-0.541416,-0.086859,-0.705281,-0.727173,-0.692772,-0.045371,-0.509239,-0.526856,-0.344908

### Resolvendo os dados "NA"

- input_0 até input_3 são categóricos
- input_X_Y
    - X varia de 4 até 556 (features)
    - Y varia de 1 até 14 (dias antes)

In [73]:
# Hardcoded parameters
num_days = 14
num_features = 556 - 4

# Verificando a quantidade de NA por feature
labels = []
aed_na_count = {}
aed_na_percentage = {}
df_len = len(dataset)
for i_feature in range(num_features):
    for i_day in range(num_days):
        label = "input_" + str(i_feature + 4) + "_" + str(i_day + 1)
        labels.append(label)
    for label in labels:
        count = dataset[label].isnull().sum()
        na_count[label] = count
        aed_na_percentage[label] = count / df_len

In [74]:
df_aed = pd.DataFrame([aed_na_count, aed_na_percentage])

In [75]:
df_aed

,input_4_1,input_4_2,input_4_3,input_4_4,input_4_5,input_4_6,input_4_7,input_4_8,input_4_9,input_4_10,...,input_555_5,input_555_6,input_555_7,input_555_8,input_555_9,input_555_10,input_555_11,input_555_12,input_555_13,input_555_14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

---
## Análise Exploratória

### Matriz de Correlação

In [30]:
corr_matrix = dataset.corr()
sn.heatmap(corr_matrix, annot=True)
plt.title("Matriz de correlação de atributos quantitativos")
plt.show()

KeyboardInterrupt: